# Generated by Django 5.1.5 on 2025-01-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_model',
            name='name',
            field=models.CharField(),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
