# Generated by Django 5.1.5 on 2025-01-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_category_model_name_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_event_model',
            name='time',
            field=models.TextField(),
        ),
    ]
