# Generated by Django 5.1.5 on 2025-01-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_add_event_model_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_event_model',
            name='time',
            field=models.TimeField(),
        ),
    ]
